### ISSUE TITLE
Manage virtual env automatically

### ISSUE THREAD

**Issue by iglikoxha** [astronomer/astronomer-cosmos#222]
Instead of manually having to create a virtual env just to install dbt and then specify the path to dbt_executable_path. Wouldn't it be neat if this was done easier and automatically. Something similar to PythonVirtualenvOperator.

This would make this operator also runnable in Google Cloud Composer where installing dbt in the same environment as Airflow is a headache since it conflicts with a lot of packages, also having a custom Airflow image with the dbt_venv environment in there is impossible.

Also maybe this should be implemented in the CosmosDag level since I suppose is a feature that will be needed in the future for other authoring interfaces since we can't guarantee that they will not have any conflicts with airflow python packages.

**Comment by CorsettiS** [comment]
This is actually a very good idea and not that cumbersome to implement since the skeleton is already defined [here](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/operators/python.html#PythonVirtualenvOperator) for the PythonVirtualenvOperator. It also makes it possible for teams that dont have direct access to the airflow infrastructure to run this library. Can you create a PR for that ? otherwise I may do it once my workload reduces

**Comment by jlaneve** [comment]
Great idea! There's another PR that's already separating out the execution methods (to rename local and add docker & Kubernetes). It could be worth holding off until that PR's merged, because that'll establish how to add operators for different execution methods.

**Comment by CorsettiS** [comment]
@jlaneve alright, once the new release with this new change is deployed, I'll work on this then ! Thanks for telling us
