### ISSUE TITLE
Slimming down tmp_dir to just the --target-dir

### ISSUE THREAD

**Issue by dwreeves** [astronomer/astronomer-cosmos#362]
# Background on Astronomer-Cosmos code

The `DbtLocalBaseOperator` copies the entire project directory into a temporary directory before executing. The reason why it does this is because usually where the dbt project actually exists may be read-only, and dbt attempts to write to two different locations during its runtime: to the logs folder and to the target folder.

# Issue this can cause

The Airflow Celery executor will execute multiple tasks concurrently on a single worker instance.

For a large-ish dbt project, if multiple tasks are executed concurrently on a single worker, and the worker runs out of space from these copies, the executor will SIGKILL all tasks on the worker node. Sigkilling the tasks means that the temporary directories do not get cleaned up, and the worker is now FUBAR because it is out of space.

So, this isn't just a nice-to-have optimization. Copy+pasting the entire project directory can cause incredibly frustrating issues for end users.

This also isn't just theoretical-- I've actually run into this. Not via Astronomer-Cosmos, but via my own Airflow+dbt implementation I've had prior to the existence of Astronomer-Cosmos, where we did the same approach Astronomer-Cosmos does for a while (create tmpdir, copy whole project directory into it), until our dbt project directory got too big to keep doing this.

# Workaround

As of dbt 1.5.2 and dbt 1.6.0, it should be possible to work around this problem. Remember the two directories that dbt writes to are `logs/` and `target/`:

- The `--target-path` flag can be set for any subcommand that uses it (dbt 1.5.0 had issues here but I believe this should be fully fixed as of 1.5.2).
- The `--log-level-file` (option for the `dbt` base command) can be set to `none`, which prevents writing logs to the file system entirely.

So the steps here are, instead of copying the entire project directory to the tmp dir, instead:

- Create a new temporary directory that will act as the `--target-path`.
- Optionally, copy `target/` from the project directory into the new temporary directory.
- Run the command `dbt --log-level-file none [subcommand] --target-path {tmpdir/target/} [options/args]`

# Complications adding to Astronomer-Cosmos

- There is no process for version-checking or asserting versioning in the Cosmos runtime, as far as I can tell. This only works with `dbt>=1.5.2`, and Cosmos supports much earlier versions of dbt than that.
- The `callback()` parameter runs on the project directory, and it seems difficult to implement backwards compatibility with that.
   - I'm not 100% sure what people are doing with that, but I assume some folks may specifically be looking to extract and dump the debug logs from the project directory.

# Open for discussion

- Is this worth adding?
- How would Astronomer-Cosmos go about adding it, given the complications mentioned?

**Comment by jlaneve** [comment]
This is a great writeup! I like this idea a lot. A couple notes/thoughts on my end:


You're right that the intent behind copying the directory was because of the read-only issue. The motivation behind the `callback` is somewhat different, though - it's intended to support [dbt docs generation](https://astronomer.github.io/astronomer-cosmos/dbt/docs.html). Today, that's the only use case I know of.


With dbt >= 1.5.2, we should definitely just create temp dirs for the target and logs directories. I think it's acceptable to use `dbt version` for this check, despite the fact that it may add 1-2s to the execution time to run the command.


It may also be worth considering putting this behavior under a flag. If someone has an extremely large dbt project that they put in a write directory, and they're fine with writing to that directory, we should let them disable the cloning functionality. If we do this, and a user disables the cloning, we shouldn't need to check for their dbt version - which eliminates the 1-2 extra seconds.


Given that the main use case for the `callback` function is to deal with the artifacts after running a dbt model, we may want to just modify the `callback` function to take two/three arguments (path to logs, path to target, maybe also path to project dirs) instead of the one argument today (path to project dir). We're also working towards a 1.0 release right now, where it'll be (more) acceptable to make breaking changes. This should alleviate concerns with any changes we need to make to the `callback` function.

**Comment by tatiana** [comment]
@dwreeves Since you first posted this, we made some improvements in Cosmos, including using symbolic links.

Since Cosmos  1.2.4, the `DbtLocalBaseOperator` creates symbolic links, as opposed to copying the full directory:
https://github.com/astronomer/astronomer-cosmos/pull/660

It was based on the improvement we did on the `LoadMode.DBT_LS`, released in Cosmos 1.1:
https://github.com/astronomer/astronomer-cosmos/pull/488

Initially, we attempted to use flags/environment variables, but we noticed they did not work for a few versions of dbt that we currently support. PR #488 tries to give a bit more context on why we adopted symlinks. Do you think this approach addresses your original concerns?

**Comment by dwreeves** [comment]
Oh, that's a pretty clever solution for compatibility with older dbt versions. Excellent work!

My guess is that symlinks would solve the issue described in this ticket.
