### ISSUE TITLE
Enable Open Lineage for the Dbt Operators

### ISSUE THREAD

**Issue by pohek321** [astronomer/astronomer-cosmos#39]

**Comment by denimalpaca** [comment]
Working on this -- related OpenLineage [issue](https://github.com/OpenLineage/OpenLineage/issues/1438).

Basically we need `dbt-ol` to be able to parse and dynamically create dbt sources instead of refs to upstream datasets. Then we also need to create an operator in cosmos for the `dbt docs` command. We also need switch on the operators to use the `dbt-ol` executable path when `dbt-ol` is installed, and, of course, the `dbt-ol` project as an installable in Cosmos.
