### ISSUE TITLE
Write logs to a temp dir when using `dbt_ls` parsing mode

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astronomer-cosmos#411]
In Slack, a user was getting an issue where the `dbt ls` command for generating the manifest was trying to write logs to the same directory, which is typically read-only.

```
20:43:06  Encountered an error:
[Errno 30] Read-only file system: '/usr/local/airflow/dags/dbt_grindr/logs/dbt.log'
```

We should instead have dbt write to a temp dir and paste the logs to stdout if there are any written to disk

**Comment by tatiana** [comment]
Users could resolve this by setting the environment variable `DBT_LOG_PATH` (https://docs.getdbt.com/reference/project-configs/log-path)

**Comment by tatiana** [comment]
I just found the original bug report by Adam Underwood:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1690490672020429?thread_ts=1690473607.733569&cid=C059CC42E9W

The problem goes beyond the logs directory since the `dbt ls` command also creates a `target` directory, where several files are attempted to be written, including: `target/partial_parse.msgpack`. This could be overcome by setting `DBT_TARGET_PATH`.

**Comment by tatiana** [comment]
A solution to fix both issues if the user does not set DBT-specific environment variables can be to create a temporary directory from where we'll run `dbt ls`.

This would assume that the user/process running cosmos has to write permissions to create/write temporary directories.

**Comment by tatiana** [comment]
@jlaneve let's align here on the approach, given the feedback you gave in:
https://github.com/astronomer/astronomer-cosmos/pull/414

A proposal:
1. If the user defines `DBT_TARGET_PATH` and/or `DBT_LOG_PATH`, we should use them when running `dbt ls`.
2. If the user doesn't define one/both of them, we'll be creating a `tmp` directory where we'll output both target and logs
3. By the end of running `dbt ls`, we'll log everything that is in the given dbt logs file (we can start by logging it using the `debug` mode, in future we can use the Airflow log level to decide which dbt log levels we want to print)

Are you happy with this approach?

**Comment by jlaneve** [comment]
> @jlaneve let's align here on the approach, given the feedback you gave in: #414
> 
> A proposal:
> 
> 1. If the user defines `DBT_TARGET_PATH` and/or `DBT_LOG_PATH`, we should use them when running `dbt ls`.
> 2. If the user doesn't define one/both of them, we'll be creating a `tmp` directory where we'll output both target and logs
> 3. By the end of running `dbt ls`, we'll log everything that is in the given dbt logs file (we can start by logging it using the `debug` mode, in future we can use the Airflow log level to decide which dbt log levels we want to print)
> 
> Are you happy with this approach?

yes, this sounds great - thank you!

**Comment by tatiana** [comment]
Some additional comments on this. I played a bit with `dbt ls`, and this is what I found so far:

**Logs path**
* Neither dbt 1.5 nor 1.6 support the `--log-path`
* dbt 1.6 supports `DBT_LOG_PATH`, dbt 1.5 doesn't

**Target path**
* dbt 1.6 supports `--target-path`
* dbt 1.6 supports `DBT_TARGET_PATH`, dbt 1.5 doesn't

So the one thing to keep in mind with this approach is that if users are using an older version of `dbt`, the custom environment variables approach will not work.

**Comment by tatiana** [comment]
What we agreed is that we're going to attempt to run `dbt ls` from a temporary directory, pointing to the models/snapshots/seed etc directoried in the original place.

**Comment by DanMawdsleyBA** [comment]
I have tried running the pre-release version to see if it would fix the issue but I get the same. I think the issue may be due to the `dbt ls` command doesn't support `--log-path` as input. (Running dbt 1.5.5)
![image](https://github.com/astronomer/astronomer-cosmos/assets/134394384/1262546b-074a-4c07-ac04-ff245aa976bb)
When I run `dbt ls -h` it mentions about setting the target path (and target path env variable) but not the log-path.
![image](https://github.com/astronomer/astronomer-cosmos/assets/134394384/10f2a8b1-4a7d-4ed4-b765-c6b03ea1edd8)
So may require a fix of dbt core first to enable the log-path as input when running the dbt ls command

**Comment by DanMawdsleyBA** [comment]
After further debugging I was able to get it to work. Turns out the issue was with dbt packages the code need to run dbt deps before running `dbt ls` (or `dbt ls` not be dependent on packages which I don't think it needs to be).

**Comment by binhnq94** [comment]
@DanMawdsleyBA I did a hot fix for my work here:
https://github.com/binhnq94/astronomer-cosmos/commit/177cebd0278c39aad92c801f653002ab708e7c64
