### ISSUE TITLE
Add authentication method for BigQuery (Service Account File)

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#43]
See dbt official docs on how to do this [here](https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#service-account-file). We'll have to create a default profile for this auth method and map the fields from the Airflow connection into it.

**Comment by pohek321** [comment]
Marking as blocked because we should really do [this](https://github.com/astronomer/astronomer-cosmos/issues/41) before adding any more auth methods

**Comment by tatiana** [comment]
This has been supported since 1.0, maybe before:
* https://github.com/astronomer/astronomer-cosmos/blob/ccfde1e6b92153c40fceb9d2814e24263707aad9/cosmos/profiles/bigquery/service_account_file.py
* https://github.com/astronomer/astronomer-cosmos/blob/ccfde1e6b92153c40fceb9d2814e24263707aad9/cosmos/profiles/bigquery/service_account_keyfile_dict.py
