### ISSUE TITLE
Fetch more node types from the dbt Manifest

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#598]
Sometimes, depending on the node type, the dbt manifest declares them in the root key `nodes`. However, in some cases (such as `sources` and `exposures`, dbt lists them using dedicated keys at the same level as `nodes`.

The goal for this ticket is to check all `DbtResourceType` items defined in `cosmos.constants` and try to find them in the root of the manifest file. This is particularly relevant since users can extend the definition of `DbtResourceType` by using `DbtResourceType("newtype")`, as part of #503.

This is a follow up to:
https://github.com/astronomer/astronomer-cosmos/pull/503#discussion_r1357377316

**Comment by david-mag** [comment]
With both parsing methods, `DBT_MANIFEST` and `DBT_LS`, the manifest is parsed in the end to create all nodes. Would there be value in "unifying" the two approaches by calling `load_from_dbt_maifest` from `load_via_dbt_ls` somehow, or have a common parsing function for both methods?

I also suggest a filter-step before running `dbt = DbtNode( ...` for all defined `DbtResourceTypes`. cosmos v1.1.3 threw an exception, because "DbtResourceType 'operation'" did not exist.

With the addition made in #503 that issue is solved, having an additional layer of "security" to avoid this error might be useful though.
