### ISSUE TITLE
Add default behaviour for converting dbt Source nodes into Airflow tasks

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#630]
As of Cosmos 1.2.1, it does not render [dbt Source nodes](https://docs.getdbt.com/docs/build/sources#snapshotting-source-data-freshness) as Airflow tasks by default.

Since [Cosmos 1.2.0](https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.0), we've introduced support for customizing how the library converts any dbt node into Airflow:
https://astronomer.github.io/astronomer-cosmos/configuration/render-config.html#customizing-how-nodes-are-rendered-experimental

This means users can already customise the desired behaviour for Source nodes, using something like:
https://github.com/astronomer/astronomer-cosmos/blob/11ce2d718483f1d4eb1bfdac659417fb66a1492e/dev/dags/example_cosmos_sources.py#L63

The open questions are:
1. Do we want Cosmos to have a default behaviour for dbt Source nodes and automatically generate tasks for nodes of this type?
2. If the answer to (1) is yes, what do we want the behaviour for those nodes to be? Should we run:
```
dbt source freshness
```

**Comment by pgoslatara** [comment]
In addition to freshness checks users can also (and sometimes do) add standard tests to their sources, i.e. `unique`, `not_null`, etc. I think a good default behaviour would be to display sources as a task in the Airflow UI as this provides an Airflow DAG to the end user familiar with dbt that is most similar to dbt's DAG, thereby enabling Cosmos adoption. These tasks can use EmptyOperator and therefore have no impact on compute usage or scheduler resources.

One small note, DummyOperator has been deprecated in favour of EmptyOperator in Airflow 2.4 (see [here](https://airflow.apache.org/docs/apache-airflow/2.3.4/_api/airflow/operators/dummy/index.html)).

**Comment by linchun3** [comment]
+1 to this issue as this is something I'm interested in.

1. Do we want Cosmos to have a default behaviour for dbt Source nodes and automatically generate tasks for nodes of this type?

I'm in support for having each source render as an Airflow task, and running all tests attached to it. This improves the visibility of a source and whether a model update failure is due to an upstream failure.

2. If the answer to (1) is yes, what do we want the behaviour for those nodes to be?

`dbt test --select source:jaffle_shop.orders`

This command should run all the tests associated to a source. I'm not sure how we should handle `dbt source freshness` though.

Add on questions:
3. How do we handle models that share the same source? Should we render 2 source nodes or should the models share the same source node?

**Comment by pankajastro** [comment]
Look like we have a PR https://github.com/astronomer/astronomer-cosmos/pull/661 from @arojasb3 to fix it
