### ISSUE TITLE
Fix ExecutionConfig.dbt_executable_path with Path instance

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#633]
Cosmos 1.2.0 & 1.2.1 is failing to run `LoadMethod.DBT_LS` when instantiating `ExecutionConfig(dbt_executable_path=Path("some/path/str"))`.

With the error:
```
Broken DAG: [/usr/local/airflow/dags/my_cosmos_dag.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cosmos/dbt/graph.py", line 126, in load
    self.load_via_dbt_ls()
  File "/usr/local/lib/python3.10/site-packages/cosmos/dbt/graph.py", line 197, in load_via_dbt_ls
    logger.info("Running command: `%s`", " ".join(deps_command))
TypeError: sequence item 0: expected str instance, PosixPath found
```

This bug was reported in the #airflow-dbt channel:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1698407966520399

The workaround is to not use `Path` in, example: `ExecutionConfig(dbt_executable_path="some/path/str")` until we fix the issue.

**Comment by jbandoro** [comment]
This was fixed in https://github.com/astronomer/astronomer-cosmos/pull/666 since if the fallback command (`ExecutionConfig.dbt_executable_path`) is used and is a Path the string representation will be used:

https://github.com/astronomer/astronomer-cosmos/blob/e23a445b30ca391842dae870260cc7ce799d4d5c/cosmos/dbt/graph.py#L217-L219
