### ISSUE TITLE
Support DAG runs with different dbt run selectors/filters

### ISSUE THREAD

**Issue by jbandoro** [astronomer/astronomer-cosmos#686]
Currently when Cosmos loads a dbt project into a graph, whether that's via dbt ls, manifest or custom it gets all of the nodes and a subset of filtered nodes:
https://github.com/astronomer/astronomer-cosmos/blob/e23a445b30ca391842dae870260cc7ce799d4d5c/cosmos/dbt/graph.py#L265-L266

only the filtered nodes are used when building the airflow graph:

https://github.com/astronomer/astronomer-cosmos/blob/e23a445b30ca391842dae870260cc7ce799d4d5c/cosmos/converter.py#L179-L180

It would be nice if Cosmos had a feature where the selecting could be done instead for a dag run. What I'm imaging is something like I mocked up below for the jaffle shop example: 

![image](https://github.com/astronomer/astronomer-cosmos/assets/79104794/24c21f7d-7b7c-43db-88e6-d8c06f984bd4)

Where a dag run could be triggered with dbt run args like the `--select` examples above and models that are not selected will be skipped and only those that are filtered will be run.

We might be able to use the Airflow [pre_execute](https://airflow.apache.org/docs/apache-airflow/2.7.3/_api/airflow/models/baseoperator/index.html#airflow.models.baseoperator.BaseOperator.pre_execute) hook, which is available in all Airflow 2 versions, on the operators that could check for the dag run params in the context for the select args, determine if the task (model) should be run, if not it could then raise an `AirflowSkipException` which would skip the task like in the mockup above.

**Comment by tatiana** [comment]
Hi Justin, this would be a fantastic feature!

It would be awesome if we didn't have to change the Airflow DAG topology entirely based on selectors - but could just mark those tasks as "skipped".

Since many users are using selectors to scale dbt projects with Cosmos/Airflow, it would be great if we exposed this feature via an attribute of `RenderConfig` - so users could opt-in during Cosmos 1.x releases. Based on the user's feedback could make the default behaviour as of Cosmos 2.x.
