### ISSUE TITLE
Support disabling dbt "Anonymous usage stats"

### ISSUE THREAD

**Issue by ykuc** [astronomer/astronomer-cosmos#724]
How can I set send_anonymous_usage_stats=False?
https://docs.getdbt.com/reference/global-configs/usage-stats

**Comment by jbandoro** [comment]
This is a great issue you brought up @ykuc since any cosmos profiles that are mapped from Airflow connections won't have the following block for [dbt usage stats](https://docs.getdbt.com/reference/global-configs/usage-stats) in the profiles.yml:
```yaml
config:
  send_anonymous_usage_stats: False
```
which means it defaults to True when not used.

There are 2 workarounds you could have at the moment for preventing anonymous usage stats tracking:
1. Supply your own `profiles.yml` file to cosmos, see docs [here on using your own file](https://astronomer.github.io/astronomer-cosmos/profiles/index.html#using-your-own-profiles-yml-file) where you could add the config above. Though the limitation of this is that you won't be able to use Airflow connections.
2. As noted in dbt docs linked above you could also use the environment variables: `DO_NOT_TRACK=1` or `DBT_SEND_ANONYMOUS_USAGE_STATS=False`. With cosmos currently you would have to use [operator_args](https://astronomer.github.io/astronomer-cosmos/configuration/operator-args.html#dbt-related) with either `"append_env": True` if you have the env var already set, or use `"env": {"DO_NOT_TRACK": "1"}`.

In Cosmos to add support for not sending usage stats, I think this could be added to `BaseProfileMapping` args and then it could be added to profile contents in the method below:

https://github.com/astronomer/astronomer-cosmos/blob/e1f34ea424b8940f1c06660554298008876ea11b/cosmos/profiles/base.py#L175-L180
