### ISSUE TITLE
How to store all test results

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#801]
I'm looking to store test results (Both the successful and failures so https://docs.getdbt.com/reference/resource-configs/store_failures won't be sufficient). I'm considering using a dbt package such as https://github.com/brooklyn-data/dbt_artifacts which works with an on run end which will upload all the results at the end. As far as I'm aware airflow doesn't allow for always run a task on run end like how dbt does. So is there any way that I can materialize the results of all the tests using Cosmos? If not currently would it be possible to do somehow? 

For added context we're also looking to integrate these test results into Atlan.

**Comment by DanMawdsleyBA** [comment]
@tatiana / any thoughts on the above? 

It might also be desirable to have a task run on end that syncs the run_results.json with an S3 bucket (Perhaps something similar to the docs operator)  as Atlan can interpret it directly. This task would have to always run regardless of if previous tasks have failed (In order to capture test results that are failures)

Although my concern with the above would be what happens if an airflow deployment gets redeployed would those run_results.json files be overidden/deleted.

**Comment by tatiana** [comment]
Hi @DanMawdsleyBA, this is a very valid use case - and it would be great if Cosmos could support it.

At the moment, Cosmos 1.3 only offers a built-in "post command" customisation via the [callback feature](https://astronomer.github.io/astronomer-cosmos/configuration/testing-behavior.html), which only works on failed tests.

The other possibility you'd have is to customise how you'd like dbt test to behave in Cosmos, using [this feature](https://astronomer.github.io/astronomer-cosmos/configuration/render-config.html#customizing-how-nodes-are-rendered-experimental).

How are you [running your tests](https://astronomer.github.io/astronomer-cosmos/configuration/testing-behavior.html) in Cosmos? Are you using `TestBehavior.AFTER_ALL` or `TestBehavior.AFTER_EACH` (default)?

From an Atlan perspective, would it be okay if those test results files were sent on a per-task basis, considering you're running using `TestBehavior.AFTER_EACH`? 

Have you tried using  https://github.com/brooklyn-data/dbt_artifacts with Cosmos? From what I understood from the documentation, it would be triggered as part of the dbt command execution itself, so I'd expect it to work.

Another feature we could consider implementing is to expose in Cosmos the ability to upload the artefacts generated in `target` to {s3, gcs, azure, etc). What do you think? One challenge with this approach may be how we'd like to differentiate between DAG runs/task runs.

**Comment by Metystes** [comment]
> Another feature we could consider implementing is to expose in Cosmos the ability to upload the artefacts generated in target to {s3, gcs, azure, etc). What do you think?

That would be great functionality, and it could be useful in another scenarios. For example, when running a bigger DBT project as a single task (to avoid overhead with starting new pods), and one of the tasks fails, we could use the `retry` command to rerun only the failed models. To do that, we would need to have `run_results.json`. Plus, it would help with the debugging to see the compiled code.

**Comment by fabiomx** [comment]
@ms32035, 

yes, FYI, I raised the same issue here: https://github.com/astronomer/astronomer-cosmos/issues/867

**Comment by luis-fnogueira** [comment]
> [@tatiana](https://github.com/tatiana) / any thoughts on the above?
> 
> It might also be desirable to have a task run on end that syncs the run_results.json with an S3 bucket (Perhaps something similar to the docs operator) as Atlan can interpret it directly. This task would have to always run regardless of if previous tasks have failed (In order to capture test results that are failures)
> 
> Although my concern with the above would be what happens if an airflow deployment gets redeployed would those run_results.json files be overidden/deleted.

That'd be amazing!

**Comment by tatiana** [comment]
Duplicated request: https://github.com/astronomer/astronomer-cosmos/issues/1259 - we can follow up once the feature is implemented there.

**Comment by pankajkoti** [comment]
hi @DanMawdsleyBA , @Metystes , @fabiomx we recently merged PR #1389, which introduces minor changes to the existing callback functionality and will be included in the upcoming Cosmos 1.8.0 release. In the PR, we also made changes so that the callback is called first and then the exceptions are raised/handled.

To allow users to try out these changes ahead of the official release, we have prepared an alpha release. You can install it using the following link: [astronomer-cosmos 1.8.0a3](https://pypi.org/project/astronomer-cosmos/1.8.0a3/). PR #1389 also provides examples showcasing how to use this callback functionality.

For additional guidance, refer to the documentation on leveraging callbacks: [Callback Configuration](https://astronomer.github.io/astronomer-cosmos/configuration/callbacks.html). The helper functions demonstrated in the examples can be found here: [cosmos/io.py](https://github.com/astronomer/astronomer-cosmos/blob/0000f80cbdb1e137b423a9297d45380441dd8c9b/cosmos/io.py). However, you are not limited to these; you can create your own custom callback functions using these examples as a reference and pass them via the callback argument.

We would greatly appreciate any feedback you have after testing this alpha release!
