### ISSUE TITLE
[feature] support for dbt clone or dbt build ? DbtCloneOperator

### ISSUE THREAD

**Issue by SPTKL** [astronomer/astronomer-cosmos#878]
Hi there, our cicd runs "write-audit-publish", basically we do 
1) a `dbt build` command to run and test models in staging 
2) a `dbt clone` command to clone models created in step 1 to a production environment. 
Can we implement a `DbtCloneOperator`? If so what's the recommended place? Any suggestions on how to implement? 

Also given the flexibility of cosmos, say if we want to change our process to 
1) for all models, following the order of the dag, `dbt run` the model in staging 
2) `dbt test` the model in staging
3) if test passes, `dbt clone` the model from staging to production

ideally, in the dag, each model should have their own task group with 4 tasks, run, test, snapshot, clone. It's impossible in the dbt cli because `clone` is a different command (but we get run, test, snapshot in `dbt build`). what's the recommended path for implementing something like this ^, I know it's difficult because given our current implementation, the environments are configured using different targets with different dbt profiles.

**Comment by tatiana** [comment]
HI @SPTKL, This is a very useful feature. I'm still learning about the `dbt clone` [command](https://docs.getdbt.com/reference/commands/clone).

Your feature request has similarities with #903 .

One of the challenges is that we may need to introduce Cosmos intermediate storage so that independent tasks, running potentially in different worker nodes/containers / VMs, could share the build artifacts needed by `dbt clone`. This is being discussed in a separate ticket: #894

Would you be interested in contributing to Cosmos in this area?

**Comment by SPTKL** [comment]
Yes, I'm interested!
