### ISSUE TITLE
performance degradation

### ISSUE THREAD

**Issue by liranc1** [astronomer/astronomer-cosmos#932]
Before using cosmos Airflow dag was running for about 15 min for a certain dbt command.
After the change to cosmos, the same dbt command is much more volatile, often taking 20-30 min.
All Airflow's resources stayed the same for the dag, and there was no change in the dbt connection details.

I also encountered some tasks randomly failing due to connection error (snowflake), that was successful on the next run. This issue did not occur without cosmos.

cosmos configurations used: 

ExecutionConfig(dbt_executable_path=DBT_EXECUTABLE_PATH)

RenderConfig(
        select=["models"],
        test_behavior=TestBehavior.NONE,
        load_method=LoadMode.DBT_LS,
        dbt_deps=False
)

ProjectConfig(os.environ["DBT_PROJECT_PATH"], dbt_vars=dbt_vars)

dbt version:
Core:
  - installed: 1.5.6
Plugins:
  - snowflake: 1.5.6

**Comment by tatiana** [comment]
Hi @liranc1 thanks for sharing this information, could you please confirm which version of Cosmos you were using before and after this performance degradation was observed?

**Comment by liranc1** [comment]
Cosmos was not used before, I was using bash operator.
The performance degradation started once I moved to Cosmos.
The cosmos version I used is 1.3.2

**Comment by tatiana** [comment]
@liranc1 could you try out Cosmos 1.4 and let us know if there are any performance improvements?

**Comment by tatiana** [comment]
Some progress: #1014.

**Comment by tatiana** [comment]
The previously mentioned PR, #1014, is for review and seems to have promising results

**Comment by tatiana** [comment]
If using `LoadMode.DBT_LS`, please, could you try Cosmos 1.5.0a9, which will be released as a stable version this week?
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.5.0a9
* https://pypi.org/project/astronomer-cosmos/1.5.0a9/

Some ways to improve the performance using Cosmos 1.4:

**1. Can you pre-compile your dbt project?**

If yes, this would remove this responsibility from the Airflow DAG processor, greatly impacting the DAG parsing time. You could try this by using and specifying the path to the manifest file:
```
DbtDag(
    ...,
    render_config=RenderConfig(
        load_method=LoadMode.DBT_MANIFEST
    )
)
```

More information: https://astronomer.github.io/astronomer-cosmos/configuration/parsing-methods.html#dbt-manifest

**2. If you need to use `LoadMode.DBT_LS`, can you pre-install dbt dependencies in the Airflow scheduler and worker nodes?**

If yes, this will avoid Cosmos having to run dbt deps all the time before running any dbt command, both in the scheduler and worker nodes. In that case, you should set:
```
DbtDag(
    ...,
    operator_args={"install_deps": False}
    render_config=RenderConfig(
        dbt_deps=False
    )
)
```
More info:
https://astronomer.github.io/astronomer-cosmos/configuration/render-config.html

**3. If you need to use LoadMode.DBT_LS, is your dbt project large? Could you use selectors to select a subset?**

```
jaffle_shop = DbtDag(
    render_config=RenderConfig(
        select=["path:analytics"],
    )
)
```
More info: https://astronomer.github.io/astronomer-cosmos/configuration/selecting-excluding.html

*4. Are you able to install dbt in the same Python virtual environment as you have Airflow installed?*

If this is a possibility, you'll be able to experience significant performance improvements by leveraging the `InvocationMode.DBT_RUNNER` method, that is switched on by default since Cosmos 1.4.

More information:
https://astronomer.github.io/astronomer-cosmos/getting_started/execution-modes.html#invocation-modes
